# Generated by Django 2.2.2 on 2019-07-12 07:08

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='people_output',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('signup', models.DateTimeField()),
                ('points', models.IntegerField(max_length=11)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
    ]
