# Generated by Django 2.2.2 on 2019-07-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190712_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people_output',
            name='signup',
            field=models.DateTimeField(),
        ),
    ]
