# Generated by Django 2.2.2 on 2019-07-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190712_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people_output',
            name='signup',
            field=models.TextField(),
        ),
    ]
