# Generated by Django 2.2.2 on 2019-07-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190712_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people_output',
            name='_id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
