# Generated by Django 2.2.2 on 2019-07-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190713_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='search',
            fields=[
                ('_id', models.TextField(primary_key=True, serialize=False)),
                ('signup', models.TextField()),
                ('points', models.IntegerField(max_length=11)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
    ]
